-- =============================================================================
-- Smart HAS — Oracle Database: Schema (DDL)
-- Fase 6: Camada de persistência Oracle + PL/SQL
-- =============================================================================
-- Entidades principais do domínio Smart HAS:
--   APP_USER                   -> pacientes e administradores
--   BLOOD_PRESSURE_READING     -> leituras de pressão arterial (dados de sensor)
--   MEDICATION_DELIVERY_REQUEST-> pedidos de entrega (AI Logistics Extension)
--   SENSOR_ALERT                -> alertas gerados a partir de leituras críticas
--
-- DER (resumo textual — ver docs/DER_Oracle.png para o diagrama visual):
--   APP_USER (1) ----< (N) BLOOD_PRESSURE_READING
--   APP_USER (1) ----< (N) MEDICATION_DELIVERY_REQUEST
--   APP_USER (1) ----< (N) SENSOR_ALERT
--   BLOOD_PRESSURE_READING (1) ----< (N) SENSOR_ALERT
-- =============================================================================

PROMPT Dropping existing objects (ignore errors on first run)...

BEGIN EXECUTE IMMEDIATE 'DROP TABLE sensor_alert PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE medication_delivery_request PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE blood_pressure_reading PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE app_user PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT Creating table APP_USER...
CREATE TABLE app_user (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(120)  NOT NULL,
    email         VARCHAR2(160)  NOT NULL,
    password_hash VARCHAR2(200)  NOT NULL,
    role          VARCHAR2(20)   NOT NULL,
    created_at    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_role  CHECK (role IN ('PATIENT', 'ADMIN'))
);

PROMPT Creating table BLOOD_PRESSURE_READING...
CREATE TABLE blood_pressure_reading (
    id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id        NUMBER         NOT NULL,
    systolic       NUMBER(3)      NOT NULL,
    diastolic      NUMBER(3)      NOT NULL,
    pulse          NUMBER(3),
    notes          VARCHAR2(500),
    measured_at    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    classification VARCHAR2(30)   NOT NULL,
    CONSTRAINT fk_bpr_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_bpr_classification CHECK (
        classification IN ('NORMAL', 'ELEVADA', 'HAS_ESTAGIO_1', 'HAS_ESTAGIO_2', 'CRISE_HIPERTENSIVA')
    )
);
CREATE INDEX ix_bpr_user_id ON blood_pressure_reading (user_id);

PROMPT Creating table MEDICATION_DELIVERY_REQUEST...
CREATE TABLE medication_delivery_request (
    id                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id                NUMBER        NOT NULL,
    medication_name        VARCHAR2(120) NOT NULL,
    quantity               NUMBER(5)     NOT NULL,
    delivery_address       VARCHAR2(300) NOT NULL,
    requested_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    risk_score             NUMBER(3)     NOT NULL,
    priority               VARCHAR2(20)  NOT NULL,
    estimated_window_start TIMESTAMP,
    estimated_window_end   TIMESTAMP,
    status                 VARCHAR2(20)  DEFAULT 'PENDENTE' NOT NULL,
    CONSTRAINT fk_mdr_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_mdr_priority CHECK (priority IN ('BAIXA', 'MEDIA', 'ALTA', 'URGENTE')),
    CONSTRAINT ck_mdr_status   CHECK (status IN ('PENDENTE', 'EM_ROTA', 'ENTREGUE', 'CANCELADO'))
);
CREATE INDEX ix_mdr_user_id ON medication_delivery_request (user_id);

PROMPT Creating table SENSOR_ALERT...
CREATE TABLE sensor_alert (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id     NUMBER        NOT NULL,
    reading_id  NUMBER        NOT NULL,
    alert_level VARCHAR2(20)  NOT NULL,
    message     VARCHAR2(400) NOT NULL,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_alert_user    FOREIGN KEY (user_id)    REFERENCES app_user (id),
    CONSTRAINT fk_alert_reading FOREIGN KEY (reading_id) REFERENCES blood_pressure_reading (id),
    CONSTRAINT ck_alert_level   CHECK (alert_level IN ('ATENCAO', 'CRITICO'))
);
CREATE INDEX ix_alert_user_id ON sensor_alert (user_id);

PROMPT Schema created successfully.
